var json_BOLIVAR_ISAIASMEDINAANGARITAMunicipio_Bolivar_Parroquia_Isaias_Medina_AngaritaIsaias_Medina_Angarita_Centros_Poblados_15 = {
"type": "FeatureCollection",
"name": "BOLIVAR_ISAIASMEDINAANGARITAMunicipio_Bolivar_Parroquia_Isaias_Medina_AngaritaIsaias_Medina_Angarita_Centros_Poblados_15",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "pk": "1", "id": "1", "código": "200404", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "4", "parroquia": "Isaías Medina Angarita", "capital_pa": "Las Dantas", "nombre": "El Pabellón", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.433300763666807, 7.652930697932883 ] ] } },
{ "type": "Feature", "properties": { "pk": "2", "id": "2", "código": "200404", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "4", "parroquia": "Isaías Medina Angarita", "capital_pa": "Las Dantas", "nombre": "La Esterlina", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.430494490143232, 7.701879735444179 ] ] } },
{ "type": "Feature", "properties": { "pk": "3", "id": "3", "código": "200404", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "4", "parroquia": "Isaías Medina Angarita", "capital_pa": "Las Dantas", "nombre": "Murciélago", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.403812617482828, 7.690816058332557 ] ] } },
{ "type": "Feature", "properties": { "pk": "4", "id": "4", "código": "200404", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "4", "parroquia": "Isaías Medina Angarita", "capital_pa": "Las Dantas", "nombre": "Buena Vista", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.444914102338288, 7.694716740898388 ] ] } },
{ "type": "Feature", "properties": { "pk": "5", "id": "5", "código": "200404", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "4", "parroquia": "Isaías Medina Angarita", "capital_pa": "Las Dantas", "nombre": "La Luisiana", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.419004277365104, 7.683567423114293 ] ] } },
{ "type": "Feature", "properties": { "pk": "6", "id": "6", "código": "200404", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "4", "parroquia": "Isaías Medina Angarita", "capital_pa": "Las Dantas", "nombre": "LAS DANTAS", "descripció": "Capital Parroquia", "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.429772854898147, 7.690429428796423 ] ] } },
{ "type": "Feature", "properties": { "pk": "7", "id": "7", "código": "200404", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "4", "parroquia": "Isaías Medina Angarita", "capital_pa": "Las Dantas", "nombre": "El Hato", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.437960481149986, 7.706177648897747 ] ] } },
{ "type": "Feature", "properties": { "pk": "8", "id": "8", "código": "200404", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "4", "parroquia": "Isaías Medina Angarita", "capital_pa": "Las Dantas", "nombre": "Las Quebradas", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.437760757163943, 7.679564401094036 ] ] } },
{ "type": "Feature", "properties": { "pk": "9", "id": "9", "código": "200404", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "4", "parroquia": "Isaías Medina Angarita", "capital_pa": "Las Dantas", "nombre": "Novilleros", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.460004946489818, 7.711473712167262 ] ] } },
{ "type": "Feature", "properties": { "pk": "10", "id": "10", "código": "200404", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "4", "parroquia": "Isaías Medina Angarita", "capital_pa": "Las Dantas", "nombre": "Alto Grande", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.452344933283129, 7.71774051752841 ] ] } },
{ "type": "Feature", "properties": { "pk": "11", "id": "11", "código": "200404", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "4", "parroquia": "Isaías Medina Angarita", "capital_pa": "Las Dantas", "nombre": "Valencia", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.421668812939515, 7.677172748622747 ] ] } }
]
}
